# ============================================================================
# Regression test — combined (MET) ANOVA F-test denominators
#
# Structure under test: RCBD with replication nested within environment, where
# Environment = Location x Year.
#
#   Source            Correct denominator
#   ----------------  -------------------
#   Environment       Rep(Environment)      <- the term this test exists for
#   Genotype          Residual
#   Environment x G   Residual
#   Rep(Environment)  Residual
#
# Environment sits at the whole-environment stratum: it must be judged against
# replicate-to-replicate variation, not against the finer within-environment
# residual. Dividing by the pooled residual treats replicate variation as plot
# noise and overstates significance — on this fixture, F 434.25 / p 4.76e-174
# (wrong) against F 24.53 / p 3.62e-08 (correct).
#
# Fixture: testdata/met_rcbd_synthetic.csv, generated by
# testdata/make_met_fixture.R (committed, seeded, reproducible). Synthetic by
# design — no real trial data is committed to this repository. The real Sayo
# multi-environment trial remains the EXTERNAL validation dataset for this fix
# and is held outside the repo.
#
# The expected values below were derived INDEPENDENTLY of the engine: mean
# squares taken straight from anova(lm(...)), each F formed by hand as
# MS(effect)/MS(named denominator), each p from pf() with that denominator's df.
# They are frozen as full-precision literals — not regenerated from the code
# under test, and not rounded.
#
# Run:  Rscript test_met_environment_ftest.R    (from genetics-module/)
# ============================================================================

source("vivasense_genetics.R")

# Absolute tolerance for F and MS; p-values are compared on a relative basis
# because they span many orders of magnitude.
TOL_ABS <- 1e-9
TOL_REL_P <- 1e-9

failures <- 0L

expect_close <- function(label, actual, expected, tol = TOL_ABS, relative = FALSE) {
  ok <- !is.null(actual) && !is.na(actual) &&
    if (relative) abs(actual - expected) <= tol * abs(expected) else abs(actual - expected) <= tol
  if (ok) {
    cat(sprintf("  PASS  %-46s %.15g\n", label, actual))
  } else {
    failures <<- failures + 1L
    cat(sprintf("  FAIL  %-46s got %.15g, expected %.15g\n",
                label, if (is.null(actual)) NA_real_ else actual, expected))
  }
  invisible(ok)
}

expect_identical_int <- function(label, actual, expected) {
  if (!is.null(actual) && !is.na(actual) && as.integer(actual) == expected) {
    cat(sprintf("  PASS  %-46s %d\n", label, as.integer(actual)))
  } else {
    failures <<- failures + 1L
    cat(sprintf("  FAIL  %-46s got %s, expected %d\n", label, format(actual), expected))
  }
}

# ── Fixture ─────────────────────────────────────────────────────────────────
raw <- read.csv("testdata/met_rcbd_synthetic.csv", stringsAsFactors = FALSE)

met <- data.frame(
  genotype    = factor(raw$Genotype),
  environment = factor(paste(raw$Location, raw$Year, sep = " × ")),
  rep         = factor(raw$Replication),
  trait_value = as.numeric(raw$Days_to_Silking),
  stringsAsFactors = FALSE
)

cat("\n=== MET combined-ANOVA F-test denominators ===\n")
cat(sprintf("Fixture: %d rows, %d genotypes, %d environments, %d reps\n\n",
            nrow(met), nlevels(met$genotype), nlevels(met$environment),
            nlevels(met$rep)))

res <- compute_multi_environment(met, trait_name = "Days_to_Silking")
at  <- res$anova_table

row_of <- function(term) {
  idx <- match(term, rownames(at))
  if (is.na(idx)) {
    failures <<- failures + 1L
    cat(sprintf("  FAIL  ANOVA table has no row '%s' (rows: %s)\n",
                term, paste(rownames(at), collapse = ", ")))
    return(NULL)
  }
  list(df = at[idx, "Df"], ms = at[idx, "Mean Sq"],
       f = at[idx, "F value"], p = at[idx, "Pr(>F)"])
}

# ── Every term checked against its own independently derived reference ──────
# Not "unchanged from before": each F and p below was computed by hand from the
# mean squares and the denominator named in the header comment.
reference <- list(
  environment = list(
    df = 8L,   ms = 946.80622560185,
    f  = 24.5339091674829,        # 946.80622560185 / 38.5917392592592
    p  = 3.62126813880836e-08     # pf(F, 8, 18, lower.tail = FALSE)
  ),
  genotype = list(
    df = 19L,  ms = 97.2009696978565,
    f  = 44.5808423368478,        # 97.2009696978565 / 2.18033048732944
    p  = 1.66532994485865e-80     # pf(F, 19, 342, lower.tail = FALSE)
  ),
  `environment:rep` = list(
    df = 18L,  ms = 38.5917392592592,
    f  = 17.6999493808519,        # 38.5917392592592 / 2.18033048732944
    p  = 8.83107771987816e-39     # pf(F, 18, 342, lower.tail = FALSE)
  ),
  `environment:genotype` = list(
    df = 152L, ms = 2.35139134259261,
    f  = 1.07845638826648,        # 2.35139134259261 / 2.18033048732944
    p  = 2.85164154410821e-01     # pf(F, 152, 342, lower.tail = FALSE)
  )
)

for (term in names(reference)) {
  cat(sprintf("\n%s\n", term))
  got <- row_of(term)
  if (is.null(got)) next
  ref <- reference[[term]]
  expect_identical_int(sprintf("%s  df", term), got$df, ref$df)
  expect_close(sprintf("%s  MS", term), got$ms, ref$ms, tol = 1e-9)
  expect_close(sprintf("%s  F",  term), got$f,  ref$f,  tol = 1e-9)
  expect_close(sprintf("%s  p",  term), got$p,  ref$p,  tol = TOL_REL_P, relative = TRUE)
}

cat("\nResiduals\n")
resid <- row_of("Residuals")
if (!is.null(resid)) {
  expect_identical_int("Residuals  df", resid$df, 342L)
  expect_close("Residuals  MS", resid$ms, 2.18033048732944, tol = 1e-9)
  if (is.na(resid$f) && is.na(resid$p)) {
    cat("  PASS  Residuals carries no F/p\n")
  } else {
    failures <- failures + 1L
    cat("  FAIL  Residuals should carry no F/p\n")
  }
}

# ── Guard: the specific defect must not come back ────────────────────────────
cat("\nRegression guard\n")
f_env <- row_of("environment")$f
wrong_f <- 946.80622560185 / 2.18033048732944   # 434.248950378865
if (!is.na(f_env) && abs(f_env - wrong_f) < 1e-6) {
  failures <- failures + 1L
  cat(sprintf("  FAIL  Environment is being tested against the pooled residual (F = %.10g)\n", f_env))
} else {
  cat("  PASS  Environment is not tested against the pooled residual\n")
}

# ── Guard: default behaviour of sanitize_anova_f_values is unchanged ─────────
# The frozen single-environment CRD/RCBD/split-plot/factorial paths call this
# helper with no stratum map; that call must behave exactly as before.
demo <- data.frame(
  Df        = c(2, 3, 6),
  `Sum Sq`  = c(10, 30, 12),
  `Mean Sq` = c(5, 10, 2),
  `F value` = c(NA_real_, NA_real_, NA_real_),
  `Pr(>F)`  = c(NA_real_, NA_real_, NA_real_),
  check.names = FALSE
)
rownames(demo) <- c("rep", "genotype", "Residuals")
demo_out <- sanitize_anova_f_values(demo)
expect_close("default map: genotype F vs pooled residual", demo_out["genotype", "F value"], 5, tol = 1e-12)
expect_close("default map: rep F vs pooled residual",      demo_out["rep", "F value"],      2.5, tol = 1e-12)

cat("\n================================\n")
if (failures == 0L) {
  cat("ALL CHECKS PASSED\n")
  quit(status = 0)
} else {
  cat(sprintf("%d CHECK(S) FAILED\n", failures))
  quit(status = 1)
}
